// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbDtTA91rcEazxebm25G747TUudwqFOPg',
    appId: '1:656371299797:web:c9076b159e9602b0cff95c',
    messagingSenderId: '656371299797',
    projectId: 'oruphones-a0ef6',
    authDomain: 'oruphones-a0ef6.firebaseapp.com',
    storageBucket: 'oruphones-a0ef6.firebasestorage.app',
    measurementId: 'G-1X2DYNHEE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1_zfiPupPs01x0UyDSyutVuG5tQCfyo',
    appId: '1:656371299797:android:02eb32a49dc66001cff95c',
    messagingSenderId: '656371299797',
    projectId: 'oruphones-a0ef6',
    storageBucket: 'oruphones-a0ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfh9iizsIMDzkYR37N6lPSZrVxTmVmRvM',
    appId: '1:656371299797:ios:10f33c52d273042fcff95c',
    messagingSenderId: '656371299797',
    projectId: 'oruphones-a0ef6',
    storageBucket: 'oruphones-a0ef6.firebasestorage.app',
    iosBundleId: 'com.example.oru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfh9iizsIMDzkYR37N6lPSZrVxTmVmRvM',
    appId: '1:656371299797:ios:10f33c52d273042fcff95c',
    messagingSenderId: '656371299797',
    projectId: 'oruphones-a0ef6',
    storageBucket: 'oruphones-a0ef6.firebasestorage.app',
    iosBundleId: 'com.example.oru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbDtTA91rcEazxebm25G747TUudwqFOPg',
    appId: '1:656371299797:web:e16345ba33c48dcfcff95c',
    messagingSenderId: '656371299797',
    projectId: 'oruphones-a0ef6',
    authDomain: 'oruphones-a0ef6.firebaseapp.com',
    storageBucket: 'oruphones-a0ef6.firebasestorage.app',
    measurementId: 'G-TPVCFRPEHC',
  );
}
